# Generated by Django 2.0 on 2018-08-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(help_text=' First Name of the person', max_length=50)),
                ('LastName', models.CharField(help_text=' Last Name of the person', max_length=50)),
            ],
        ),
    ]
