# Generated by Django 2.0 on 2018-08-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Door', models.CharField(help_text=' Door No of the house', max_length=50)),
                ('Street', models.CharField(help_text=' Street of the residence', max_length=50)),
                ('City', models.CharField(help_text='Current city', max_length=50)),
                ('Pincode', models.IntegerField(help_text='zip code of the locality', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
