# Generated by Django 2.0 on 2018-08-07 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App1', '0002_address_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.AddField(
            model_name='user',
            name='Address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='Avatar',
            field=models.ImageField(blank=True, null=-1, upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='BasicDetail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='others', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='Pincode',
            field=models.IntegerField(help_text='zip code of the locality'),
        ),
    ]
