# Generated by Django 2.0 on 2018-09-09 09:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App1', '0003_auto_20180807_0753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Profile',
        ),
    ]
