# Generated by Django 2.0 on 2018-09-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_auto_20180909_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='BasicDetail',
            new_name='User',
        ),
    ]
