# Generated by Django 2.0 on 2018-09-23 07:16

import RestApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Door', models.CharField(help_text=' Door No of the house', max_length=50)),
                ('Street', models.CharField(help_text=' Street of the residence', max_length=50)),
                ('City', models.CharField(help_text='Current city', max_length=50)),
                ('Pincode', models.IntegerField(help_text='zip code of the locality')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Avatar', models.ImageField(blank=True, null=-1, upload_to=RestApp.models.filename)),
                ('Address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestApp.address')),
                ('User', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
