# Generated by Django 2.0 on 2018-10-02 12:15

import RestApp.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=RestApp.models.postname)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 10, 2, 17, 45, 0, 80093))),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='Address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='RestApp.address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Avatar',
            field=models.ImageField(blank=True, default=None, upload_to=RestApp.models.filename),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='Phone',
            field=models.CharField(blank=True, default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='User',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RestApp.Profile'),
        ),
    ]
