# Generated by Django 2.0 on 2018-10-07 05:33

import RestApp.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0004_auto_20181007_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 7, 11, 3, 36, 28798)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Address',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RestApp.address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Avatar',
            field=models.ImageField(blank=True, upload_to=RestApp.models.filename),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
