# Generated by Django 2.0 on 2018-10-07 05:35

import RestApp.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0005_auto_20181007_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 7, 11, 5, 17, 940222)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestApp.address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to=RestApp.models.filename),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
